services:
  mysql:
    image: mysql:8.0
    container_name: mysql_chanme
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3323:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_chanme
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    build: .
    container_name: spring_boot_chanme
    restart: always
    ports:
      - "8078:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_chanme:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      # FastAPI를 안 쓰면 아래 줄 삭제해도 됨
      PYTHON_BASE_URL: ${PYTHON_BASE_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network_chanme

  fastapi:
    build:
      context: ./fastapi-app
    container_name: fastapi_chanme
    ports:
      - "8077:8000"
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql_chanme
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network_chanme

# 네트워크/볼륨 정의
networks:
  network_chanme:
    driver: bridge

volumes:
  mysql_data:

